name: Publish to PyPI

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Hatch
      uses: pypa/hatch@a3c83ab3d481fbc2dc91dd0088628817488dd1d5

    - name: Build
      run: hatch build

    - name: Publish to PyPI
      env:
        HATCH_INDEX_USER: __token__
        HATCH_INDEX_AUTH: ${{ secrets.PYPI_TOKEN }}
      run: hatch publish
